d3_list = [
    "QLFdFCdlLcVqdvFLnFLSSShZwptfHHhfZZZpSwfmHp",
    "rTJRjjbJTgzDJjdsRsfwtfNwtfmZpZNhmmzt",
    "bMdJjsjglnVMFCCc",
    "BZvZMBBBMTtZTgcCPdgtgQCrrV",
    "VspNDDpsGDGnRmRpRplQdrrPcPCjgDCcPQCQQj",
    "RVnsmspnpwFRlHGRwHHlnRSThSSvBTbFTZMqTMZMTZFh",
    "ttffrVJWtWpgtQnZGVnNSLTHSZ",
    "jRsjjmhdRcjcRsFcdwGLMZSnHMTSMNZN",
    "RjczlvjhPCcPjcvRpbglWplJBblqrGgq",
    "NwCWwdNQNDCwGpWNQwmJtZgPZrdJgLZcPhLddr",
    "blqpnFTqrLbcLPtV",
    "MnjqSSpqlFRvSqNDGHvWHQDwfWmm",
    "jfLljlQhDLmlrMJQtJTJrQqQ",
    "NpBbjjsdMCgCCMrb",
    "dwspwGnSHHGsGzDDlFDjVWjfZWnP",
    "wQhTZwvpZFZdqWLnnwSrWC",
    "mfDmMFlDcPLdgDSCLCqg",
    "PmzclsMclMlFsHHsJZFHpT",
    "LfLJWNdJnBLfhndfWdZqcgDZgSqgCCSSSLDF",
    "bQVQmrrjPqQDZSZBCQ",
    "RRtGjVmRsPbPrrnNNpNHHnBnpHns",
    "PfbGNwGBwNcPTbGNQFBVjsjztVztVjHV",
    "hrdCJhmlJhZrLDRmghrmDrzqFsbgtbHqnznzznQtbjtz",
    "WdZdDJCDmrJmLZrLDLDZlClcSccwSPbNPfSNWfGNNWMGNc",
    "QwrnTSgqgFShSdfHPdbS",
    "BGdjmMmZMvfhvCZZPf",
    "BzGmzVGGGzmzGpVBtdnQqqdTQQDDqrpR",
    "PPRPwLQlLtbPmbwgJhrSssNlhhrgsZ",
    "fFTdFvTMNfzVnFqdnjgSSjjsSjhghpJs",
    "dvczcFzNTWVWMFLcLbQQwmbHLCLL",
    "HhLLDfMmTjsjmLmhsmmfZMjGtpGJtdcvnCWtZJcWGddttW",
    "gwrwwgzwgDpJddrJDr",
    "SBwBBbgVsVmRRhDM",
    "SZdmfdZRTQZTQgHVVGGRqZdVCjCcNCNcJRWcCBbJjCPCsNsc",
    "FnhzMMhDDFlzlnvpwMLrMDCsbcjNJbcJbBcBfPhCNbWj",
    "wzwnpDDnLvFnLlttLrzGgTVGQqZtTqSqSdfZTg",
    "FJJWWWrCGWdmzFlTVqqlMhmvVlNh",
    "btpgtfjZjjhgggrNMThl",
    "DpwpfRZDZwwfwjsnjfsZnnnwGcCRCHcCCCLGHLWcrcFCWCHW",
    "ljHHHBtjQthchhZpqqNt",
    "FTmJnPFwzlJPmzTgTgbFwJbMCpbMchhhqbhWCDMDhZcppM",
    "JwlFGwVGnFFGBGjdSsfdsG",
    "QsvpGhjGgswvjjwjjjvPpThJfLZCCLCSSLbFLStCFCSgtH",
    "mDrzdzMqqnMrDMmZnqnzNVRCStlCHFSCtJqlCLFCFLfJfJ",
    "mBDzNRWBDDMBpGsZcGZWGjPp",
    "SlLQhQsvvttFlWsWcfHHMTJfwSHwTfTf",
    "VZmmrRDRfpTHJcRf",
    "jzBnDDgjPchWlsQsBW",
    "LTLVdTSLNTLnTSnrWvdwswsfmJwmwGsffH",
    "FbgCbRRppCpPbgMcZvCcGftGGltwHwGtplQQsfJw",
    "CRBMCvZZRgMgBbDCPcDrjLzWLVrSSzShSSNrBS",
    "hVJJjhjRVRZjQvDfBstsBVNBdwstHsld",
    "pCTCcMqCThTFLFFPWcWSPHtwwdmcBHHmNtHdmwmwBl",
    "rMTCCWPLLPCMFhDnDrjzRrfDJD",
    "pqMpCvMchvFNWSBdVNqQ",
    "zDRJJDGJJtNtmGRRWVdFWWVdSfjb",
    "DDJLmnJmzwGmGLTPhTCNpgcrpv",
    "cpPpbPWVprWcbJrrwpCwwdWrvNNFRqzNnChgqFzFnZvqFlzq",
    "fTtHLfSHSsNDGLSmsLvnhFqzhzlzDhhvRlFz",
    "mSMLHTQTmHMSfBSMTPdBJJNNVddrVrbjbJ",
    "zpCpBTnFgFbncznbblzdhRswdlJsLllJdw",
    "QqqmtWVPWvHDVmqDhjsljwRhlZldhRMQ",
    "tWSHDmVfmrtPHVgGRRbgTRpSgpTc",
    "ssTbzFRtPRwTFZtvbPRMhndBqMMvMBHJnnHMMd",
    "WQVWzlGWVBqqdMQJMq",
    "pVSpSSgLfjDzWrLGWWjDzzfLtbRFFNtPZRssspsNRZcRsNZb",
    "jnPzzGlnnznWnzhvGnnpVFrZmVFcgjrrmZRFtj",
    "fsbgTdwdqBbfwCptVtdZRcrRCp",
    "gsMbgfHsBSwsGhhJWMLnWPPJ",
    "bpmbJpNbbbNGGmRJzJTsfdsvsNdglfhssCvC",
    "hWLwQjZjLhjHFFBLZldvvflrvtfjCrfjlT",
    "QWVQZZFDcDJJhJJc",
    "RmRghgRlNgfGGRmdGqhsgsZFZZpBvHpZppHcgH",
    "tbLCDLnLtSbbbjtPtMLtDPTvHHBpcHcsHvTcHsmZcF",
    "rSLrMJzDznzGmhNlVwdrRr",
    "vWjljMWcnSSpjmzbJVzJrTCmtGJV",
    "NZDDQLRqPJrPzrprTC",
    "gqDqqwpdHWhlgnjH",
    "ccptcpstDvbNvHbLNRZZ",
    "dFjhdnjQFJlFCQSjgngJPJgWWrRNWNRtNCzrVbRzNVzZZL",
    "PhThFSPPSpsmTcqMwt",
    "cLcLlMhGMGcpGzslHFHFvnHlBDvWbT",
    "VHdQwqPJdPwjJPdPQRrmjjjQnTFrbvNWFFffDvbvvNDvbBNN",
    "RwRJCHmmdQJZZLzGphcCtz",
    "hVvFVjvjVWmFRQVZqTpqtwQpwpqZfp",
    "gvDlSBDJSlPLcLdDwzwtptqTTTzwcCCt",
    "JgrJGbLgvnWsmvVr",
    "rwmqqRqrnHQGmnjCCqCzdBzCBJBz",
    "hFLgbWWPWmvtLhPtgpcdjJdcBJdpJjDsgp",
    "lvfhSSPWtTNTTZZmfr",
    "bHDDssRHsjNMbJjJLQJsbTtGvSCzCGQCTzGvSqSBzT",
    "mmVrwhmmpfPStnTSBnhStG",
    "pcwrptZcgFcmpgHRDjjZlDJsjbbD",
    "JJRrmFqJMdFFJMjjJcqGgzSCSHSCscPCHPHGZc",
    "VWpWptnvSmpPGCHC",
    "vQnDLBmbntvLBbnlldTQFlJlFFrNRd",
    "LPDftnHFQfwmBcBGmc",
    "CVqRsdqvdrlsCVsNvqwwSpTNSSDSDDBBTTSN",
    "lqlDRddjbblRbRqrlRRjsbvghHHnPQWjHWQWZHPHWZhFnP",
    "bwQsDcgsJqcsDpcQRQnpqtVSVvgSMMMfMvfVBVfdvM",
    "CGZFrHHPrTZNGGZZHmCZHlVfjfzjSfzBtBBNSBVjvntf",
    "ChrCCLGrTlhJnhDncRbp",
    "nmFnhfTQjSzfjddZWsRRRFRFGl",
    "HDgCwgtQbZlHsrqHHr",
    "cJPCgCCPbpbgDMPvMQnjmnhTfmzLpQQmjz",
    "QFHSQdNMCSgcSgFtttPNFJpCpnTjZlbblpppZplZjz",
    "LqLsWMRRfrrWMmMGpbTnbppbZnTjpnmm",
    "fWBrMqWsGswGfGRMMwrLgtPPdNFBQPHNHNPPcFPP",
    "dngbSppJSSppbVMZQQMjqfQQgwcl",
    "TWmSWtvCRCWjwfjqQqMstq",
    "FhFvRzSTNmhHnVPhGhBJdBpB",
    "gcHPgzGmPPwTsSTsbwbdWD",
    "QjBLLfVhhBqqBFQLrLjVFlNpNDtsSWTDdNptdbqbdS",
    "jCMFLVjFBFjJJLFFMVBFrLnvPzHRmHPGnGWWcCvzHRZm",
    "PDPqWWjhPpPbCsjwjTVbLT",
    "SrtCttGRMddSVwHFSs",
    "JtfvttmrGMRRJzJCqhqqqWQZhCNgJZ",
    "ChrCVFQCVQlwQNwpQcmmcjmWBmddghjjdW",
    "sbDTZStTqqfSBggPmWjWWNsL",
    "THqqSHDTtZTDTHZZbHTzRzFvlFCVprFprQVnCzNppQrz",
    "PdfWCwMWjPSrdgCMnnlGsGQvvpJZvFGnps",
    "DmBhVBLbbVqVBzTRLBRzzTLNNpRQNNZQZppZvlQpZvllvF",
    "zVDtVHBbbTbzDbrjgWjMPtMWPMlj",
    "JLsTTNDsgTMNvDQpLpGpLGNJShrfzCFnSnSrnfzCfTFhWrfw",
    "ZcqrRddHZZVRfzWnVWCzWFnn",
    "tZHZtrHHPdRtdHlcccQggsplpJDNvMGNGMss",
    "cMCLfStfMTCjPMPcGzjftMbgsRNmRgmmGsmnJbNJbghJ",
    "QHVVWrFFWZNShHSgbSJm",
    "qZwwrrpqpZpZFvqrQdFlQVSwLBMBfTTLTjLBCcdTMzMftPPB",
    "SwsdBTvgvJLPNptpCpCmBDtn",
    "wffrzwGFWFNZWpjWZnNm",
    "zrfflbRwJPhbPbsS",
    "HjHHRtwjnjRblQRttHwQGvGWNNBWvqGzfTvfNN",
    "FmScCcrsdVZrpBrVcCVFzffvzzmWGLWgqWqgGWzW",
    "SFVSDDBdsdDSJhnjJltJbPtHRM",
    "FjGFVqWrzQFlQrZzGQzFLTvfwwTgMnvcnbRMLRdnfb",
    "CCttSNsSnRfgncSg",
    "CNspmDBPtPmJJNBJPNpDhQZVzQlhqrGZflfVjQFrQj",
    "dNNdHWcmdmPPptmmWHpPTFFjJPGrQsVsPQGGGJVDrVVGrS",
    "MhZlZhlgflgfnfDtjbjJGbtnVtGS",
    "LtZqlzhzqMZWHHLwdHmFWp",
    "llNRlfwWRwwLlwFNNgRrVCBjdjCVdjpWjtVWCD",
    "HTQqzPqzQPmhhmSPznSsssJtdnMZddtMCjprtMjCnBVnjZ",
    "PzHQmqsGSJPSmQqPbfwNcgNbNgNfBGwR",
    "lPdzlZPzQzMZQGQrTZvvpjHTTpfsTTZb",
    "zRShhtWRnqnqSNRnDTTHvfNJspNsLpTsjL",
    "hBVncVtDSnhDnDBBtGrlzwmmMlGmVrMdrP",
    "HPTZVHVPlHDPlfgnjJFdJdjPjSPqCS",
    "hLRRBhwGhqbtmsRSSSjjdMJjnJGSMj",
    "QrQtqrRrcQDgVglc",
    "ZTwbbZdchZZjmVWHTrHWBVJtBB",
    "glslCDqLLDfGRqlsgLssfrCHBHFHmrHBBppFmCJWWp",
    "fRzvvvgGgNSNvmQbSQ",
    "qPGGPwCTqTzHCvPGqWdLFLssLpstLLspvd",
    "njJchhcbjbDrbcLNlLrpWWrLLHgp",
    "DQhMMMJQMQJnVbbnRHSMPwZmGZPZRTRCwTZmZGwz",
    "zzGNfPbcgdPqLrqvWWVzMq",
    "DGmJtnJTJRhhJMhCQqCLCLrrLM",
    "ZnHDtSZlTBHnBdccGSfGcwjjdb",
    "FpZDpQZDvMwZpCCMdCBPpJGPPLgJGGLffJJL",
    "jlbswNrlPPJJfGlf",
    "bnNwqbHnNwRSrqhbdCcmHddQzddFDdvZ",
    "gbQQQngWPVVtvvPQNVNvWWSHGwDsCCmDtHSlmrssDmHs",
    "fqhMLFFMMZqZMRZqMjRMqLJSCdFlrrldsDrCsDSSHHGCSC",
    "MJRZLZLGMcTqczjNPzNnzPvWBVgNnP",
    "gqdbBffTvlRHbwLl",
    "nMMQJQpGdsFpQsJzNMRLLDlmLLmjFFmLjDRF",
    "pzGMnVcMBfTdtBBV",
    "WSbfmrrrrWdbWmdfDSSStmHjtMtvCLVnqBHCVGtVGnMM",
    "lRcgFRZhJgnMLjvGgv",
    "lcvwTcFTplvwphzcTTJTbsdsPSPDdbmzmDSWPsSm",
    "bbdTjTQTQMsZNqqhJrZslg",
    "jFGVjwfCPVGfwjCVqWhWZFgqWrglllNN",
    "PjfSPzRBjCCfSBCGBLznTndHcdMLbMmmdT",
    "wSVMJSVccdGwGnsgbVTTbRsCRNgN",
    "rHjhHLmrhPJrqjNTRDgBbbRRRs",
    "zqmPPqqpPLzltrMdJcZpfdpGWWJJ",
    "ZhrBBJGrgJhGHttGGVPPcPPF",
    "cnzLqNssfRnpfWqsLfcfWQNMbMVPDtnDtbHFtMbPtVPFFM",
    "jfqzCCLsWQLcjgldjmljmgTd",
    "wghGSSGZPVwgqtwtwCCtFFMM",
    "BvbspnBznvvWHWHHHbCQptQFQlFcqMClqLLq",
    "JWzzsJHWzfWjJrvMBWHBBGDmVDrVhZmmgSPSmZVVrh",
    "ccRMJRsjjgJgcPCSCCVCwsSWVNzp",
    "WQQqnmrBWtqWqdSbVwwBSpbbCSBB",
    "QvDqmqqmgWPWjPvW",
    "msqpjDWspRWwvFvDWWhnbbJfPzFQblJJPlnz",
    "gGGrMTgLVBsBBLdsVTrSCBffHQfdHhnbPPPPffndlbzh",
    "ZCVsCGSScsLZpwNpqmZRqW",
    "PPsGmJPVPQPZmsQCVPJPnPCMDcTcdqDDTqvFhvnTjRDTDchq",
    "BdrtzNBLHStHrdrlwfNThvFhcvbDccThjbFBqq",
    "SSgdHNfSHHgzLHtLNWSPQQPMQVpmmppVCmQZCW",
    "pPssrWWLdndHPJdd",
    "QNQFTLNBFTzzgjfGTjffFNZjCSGnHDnSDJHnDScttDCcDnmd",
    "FVzVLZwZZgswqqrbphbR",
    "VpWCZjCwWnppZpqnhNjjNZjFLtLzQJHdHLQRzWLRzRztHJ",
    "DMGPmPMgTSmsgQzRFbdHRLJgdn",
    "csDMPMGDDvMSSPnDTvrDChhwljlqNNjchNCjNVcf",
    "WpGGmbSGpVWWpjMMTNdfCFNdFfRNwNSF",
    "JsQztzrvrJqsTTRbbvFBhhhv",
    "cLrDqLccsLqbDHGpZWDHgjGlZW",
    "QGMQJMmsJmMCmmqjsRvLvvdgvgVvDVdD",
    "BDcrcNbNppwTpzRdvvchhFvfFv",
    "plBBwWrbpQHDjGmGJl",
    "mzFlTdmSDzrPvCJqqDVVNC",
    "hfRmhgjRhnfwnRHcnhGGvPJQPvvfLfQvNLGv",
    "BhhnjMgRWghpwjRWMRjrZzdbSbsdstTrltdmMs",
    "bLLnbqjpvplnDvNlqpqBWJZSdPJCNdJJThhSPhTd",
    "HFwHHQMMFHGzGwRPPJPTWthTZtJSQr",
    "mfWMHFHWHmgmFcwGwwpbDljqjBDcDnLcVnlb",
    "wBrWBwSWRJMBwdZnPQPgFnwGVF",
    "fLjfbsvDDfvvqqGqZGqmPQgqTGGG",
    "vZLsjzjjZCzJWRNSBR",
    "jTRbRHHqPqTRBHqdjhgvgghhZQdDvvgvhC",
    "WLWWzzFszsmNFGWSFmMrpghCtZvhlQNDgQCDgctC",
    "FJsLsSrDmsFSDLWrzJmmMsGqjRBVbJTBVPVBbBqRjPBjHn",
    "QbwwnDDQDcDfSbDbfhhrvrCtJMvJSCvvJh",
    "FWRjjLjmdZWdWNBFNWNlNQQrMGvvMGgssGvQRvrMJs",
    "BjWdlBpmdmBWFWdpWfPfpVnVwfHpqPQDbq",
    "SqrvlMldqvSWdGPTGzWpWpzpHP",
    "tRwmhtbsRRFsLwGGTVDHppTNdbVp",
    "FRCRQdCFtCLmBhCcmmQdhFdCvnfjffjZlZnjSnvfcSrrgMgn",
    "GQQtNJQWWcqPPhMMtwqD",
    "WpWLlBWZCvhjwMMZqDDP",
    "WgvmLVmHCbpppLgdllHddvCmFGzGnfsJJQJsJncSsccFVffF",
    "HcSsSlTTvvPPWWNMWWgPTPPbGbbrwJQbrrDphrHJJRpRhp",
    "ztfLqqzmRwDGlLDb",
    "fdVtmqjdZBmSvjsPSWlTgv",
    "DPvDhhMRRMhRNDLPMNsbwHwrjgnddqddrWdPtHzr",
    "pcBGSpcVBfJWCcmJGGwHtzgrrtwqzdrtrngG",
    "mllBlBZmMlQWRbQv",
    "SGZBSFMZllJWmzvfpp",
    "NTqbNrhHNHWgNqHrNhNQbbjHJLcnfnzLLnLmfcfccJcfQLcL",
    "HggbTNRRTHqqbVSGMSZVWDMDwVPs",
    "SBsSlvbPlFPvRlbPsMFZLgVLrLsJVgzrCJfVCH",
    "jcNddNdGzZrVgNVJ",
    "tTGwdcmWGdtwQmwmwZdwSlhBPbhPTBFRhlhSMFMR",
    "RzStzTzzvvQvSHVvhVgBqMMFqhPM",
    "ddlLLwNVLWLjbbLrjrbWrwmlhcFmBGgFMMPgBcGBBqPhggMs",
    "dLwdVCVWWdfNwNwLrWrbfbJNptzDDHRnHptHtznHTppnQCtR",
    "RzcfMBHLzpDQFmnDSWNB",
    "dbqjtjVqJZZGjPGJCPGbPndNNDglrmQmNSDgSlSSng",
    "hjCTqhCJbhVCGNvMcfvhfRLhvchz",
    "sDDqDMtqshJhPvhhCpSCCWlZHSWp",
    "bffRcbBGGTwGfGfbNjgSHZSgWwplHCClZZ",
    "RTQBbcnbRNmGbGTQLbmbJVqLllsDVMsPDVVvttMd",
    "nbLBjnqwgfRRBgBwnllbLlwScvPdZPcScZPcdFZJPvZPvcMZ",
    "tChQpphHrrHztssZdcDJcPZcMvWv",
    "hpTHVMQMtQtVpzBfwjfRnfwfnjVl",
    "ljJlvvJQlrlcJcWpPzgthnPnzMgpgSpC",
    "smtmZBmHZTVttHmqFqmzCSZSdndzShPNgPShgP",
    "bVqFHLqLqfHHFwbBLHcwDQrDrtjlQvGjlRQQ",
    "pwhVsPvVVCFtmhPhzqGqqZMZvGTTTMlGWM",
    "drrrrDfDRrNQdQdrRrBdjGWqWqWlGlGtlGbGZGBTLc",
    "tSDfgnHrdDtVSPSshJCSPh",
    "WlWlDqhglLhsdgrcbFdJJpPpdBbB",
    "ZQZvSvzRMSzjZjvZmMMpbFPQFVBrVbPcpbJFLB",
    "SwGZmjvCRSMRjMzZvRnstHftNfswHsflLhNWHf",
    "jsprCvGRQrtjCsQrGsrzvGHhgmHVmHZgggmMGVmhMbHm",
    "FFFdDSdwSffJWqqMzzMmDVbZ",
    "LLcdcfcfPwwBzdTTdtvlsrjCtvPvprnsjR",
    "MvtSqNSWMzjwzFTD",
    "ZRPlcRpQszNgszNwVT",
    "bcZcrcPlcPLLLZllPlbcbLSBfWCvHvWWNSmSqNqfWN",
    "rNdZpMGnddgggwHwzRPCzDDD",
    "vcvhcTLhZLhLPCPHPDPPVvzH",
    "LTmBmthWBchWLttttFJFLlFnGJNsfpdjNsnMnMpnpZdssn",
    "ZHWFCvqBDdqqqCTDHHBWrgppTMhhVpspMPQcSgQVPS",
    "jblbGffntRwltfMQVrrQscphfg",
    "ztJrGtbwGztbmtzzRGnRznWNNCWmHHdFHdFNWWHHqCqZ",
    "WGWSSZvVvqmrmzPm",
    "NgjtwFFlwDsFghNsMtlcjljcPqrQHcZzQznpQQprnqqzHQ",
    "tgMCwNhtgbdLZRbZCT",
    "PQSPQrSGZnGnVFhpVhRRlvLvBDRV",
    "tjctcjTMMpDTvFTlRD",
    "JCftsccFCcmsJJGZGGmPHnQrGwGS",
    "TrjRFFRnpnRCHNFSjSRrffJvJfzqQBsjqQqzzffd",
    "ZtlgMDhZhgmGDLVZLlGtLPqdQQvvfBJJqzzBPdMzdd",
    "VlLDgLLDWtGZwgtRNTNrFTqCwqHTrr",
    "LpcDFDMMPjMLLjpcDGCHgHssGHWnbCBWBHvm",
    "QfZhrhVVdZThlZlfVvVzZrTbgQnBHsCCHgJBsCsJBHmBmn",
    "wwtvfZztlTVlhtrzzlLNpFFRjMPDpRcPFwRj",
    "VzZhhQHQJJWJSSFWDGclbmNPgglPgVGc",
    "ddBTqCjjBCcrqrCRrwGPGmmDGmbpBGNpNNgg",
    "CRMjwsjwsLdLRrQFJSvMFMWZcHFW",
    "JgJJPvtrhRPQQzSRMQFFSF",
    "BLqsjsdLsMBqblnsGbBqVqdwSQSCSWwNFwczQWCNNwNCHn",
    "ljqbpLbbdDlbDbqDDVtMttTTgpJJgThhJrJr",
    "nflndmjbSnlTQGwvWGPHGRGj",
    "NtstcMcDJMvwgHfFvDgR",
    "qqqpLrMsLLqLNNnzbrdlbZSrznfz",
    "ttZCCFjNjnPVCFQPPFbbStrzqzqrrrcwtmJJ",
    "gTTMRMTWsTGGTddHTTbBzBLSmqbbJGzGmqqb",
    "HpgpMTvRhHHTRDhMsHdHDRhjJlVPJjNFJnnFpQQVfPCjnP",
    "VqJVQPpjQqPBbHwldmLfVVmd",
    "tMGvrzzDGCDDddwLbgLvLwcm",
    "TWDWCzTZDGMZtzWWtsFhbRRqRQRjhbNQBBTh",
    "zgLgLHnnzCCvnsHSsZBZBsTRdD",
    "rslllhJjcQNNGjpWJlSRTRdwBVSSNTPVSdPB",
    "jGrGqjJfqccrfqGcGplrJpFvzggqmCtMzmsMnvMvvCgm"
]
priorities = {
    "a": 1,
    "b": 2,
    "c": 3,
    "d": 4,
    "e": 5,
    "f": 6,
    "g": 7,
    "h": 8,
    "i": 9,
    "j": 10,
    "k": 11,
    "l": 12,
    "m": 13,
    "n": 14,
    "o": 15,
    "p": 16,
    "q": 17,
    "r": 18,
    "s": 19,
    "t": 20,
    "u": 21,
    "v": 22,
    "w": 23,
    "x": 24,
    "y": 25,
    "z": 26,
    "A": 27,
    "B": 28,
    "C": 29,
    "D": 30,
    "E": 31,
    "F": 32,
    "G": 33,
    "H": 34,
    "I": 35,
    "J": 36,
    "K": 37,
    "L": 38,
    "M": 39,
    "N": 40,
    "O": 41,
    "P": 42,
    "Q": 43,
    "R": 44,
    "S": 45,
    "T": 46,
    "U": 47,
    "V": 48,
    "W": 49,
    "X": 50,
    "Y": 51,
    "Z": 52
}
